up

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -62,10 +62,13 @@ jobs:
           args: --release --out dist -i python3.11
           before-script-linux: |
             if [ ${{ matrix.target }} != "x86_64" ]; then  
-              sudo find -type f -name "opensslconf.h" -exec cp {} /usr/include/openssl/ \; || echo "--------------opensslconf.h not found"
-                       
+              sudo openssl version -a || echo "--------------OpenSSL not found"
+              sudo find / -type f -name "opensslconf.h"; || echo "--------------opensslconf.h not found"
+              sudo echo "--------------opensslconf.h copied to /usr/include/openssl/"
+              sudo find / -type f -name "opensslv.h"; || echo "--------------opensslv.h not found"
+              sudo echo "--------------opensslv.h found"
             else
-              sudo apt-get update && sudo apt-get install pkg-config libssl-dev clang libudev-dev librust-openssl-sys-dev build-essential -y
+              sudo apt-get update && sudo apt-get install pkg-config libssl-dev clang libudev-dev perl librust-openssl-sys-dev build-essential -y
             fi
       - name: Install x86_64 Build Dependencies
         run: sudo apt-get update && sudo apt-get install pkg-config libssl-dev clang -y
